"table_name","column_name","data_type","character_maximum_length","column_default","is_nullable"
"tb_analise_concursos","id_analise","integer",NULL,"nextval('tb_analise_concursos_id_analise_seq'::regclass)","NO"
"tb_analise_concursos","id_loterias","integer",NULL,NULL,"NO"
"tb_analise_concursos","nr_concurso","integer",NULL,NULL,"NO"
"tb_analise_concursos","tipo_metrica","character varying",50,NULL,"NO"
"tb_analise_concursos","valor","double precision",NULL,NULL,"NO"
"tb_analise_concursos","dt_analise","timestamp without time zone",NULL,"CURRENT_TIMESTAMP","NO"
"tb_analise_concursos","frequencia_media","double precision",NULL,NULL,"YES"
"tb_analise_concursos","numeros_quentes","integer",NULL,NULL,"YES"
"tb_analise_concursos","numeros_frios","integer",NULL,NULL,"YES"
"tb_analise_concursos","media_intervalos","double precision",NULL,NULL,"YES"
"tb_analise_concursos","desvio_padrao_intervalos","double precision",NULL,NULL,"YES"
"tb_analise_concursos","quantidade_clusters","integer",NULL,NULL,"YES"
"tb_analise_concursos","maior_cluster","integer",NULL,NULL,"YES"
"tb_analise_estatistica","id_analise","integer",NULL,"nextval('tb_analise_estatistica_id_analise_seq'::regclass)","NO"
"tb_analise_estatistica","id_loterias","integer",NULL,NULL,"NO"
"tb_analise_estatistica","num_analisado","integer",NULL,NULL,"NO"
"tb_analise_estatistica","frequencia","integer",NULL,NULL,"NO"
"tb_analise_estatistica","recencia","double precision",NULL,NULL,"NO"
"tb_analise_estatistica","media_posicao","double precision",NULL,NULL,"NO"
"tb_analise_estatistica","dt_analise","timestamp without time zone",NULL,"CURRENT_TIMESTAMP","NO"
"tb_historico_jogos","dt_jogo","date",NULL,NULL,"NO"
"tb_historico_jogos","num1","integer",NULL,NULL,"YES"
"tb_historico_jogos","num2","integer",NULL,NULL,"YES"
"tb_historico_jogos","num3","integer",NULL,NULL,"YES"
"tb_historico_jogos","num4","integer",NULL,NULL,"YES"
"tb_historico_jogos","num5","integer",NULL,NULL,"YES"
"tb_historico_jogos","num6","integer",NULL,NULL,"YES"
"tb_historico_jogos","num7","integer",NULL,NULL,"YES"
"tb_historico_jogos","num8","integer",NULL,NULL,"YES"
"tb_historico_jogos","num9","integer",NULL,NULL,"YES"
"tb_historico_jogos","num10","integer",NULL,NULL,"YES"
"tb_historico_jogos","num11","integer",NULL,NULL,"YES"
"tb_historico_jogos","num12","integer",NULL,NULL,"YES"
"tb_historico_jogos","num13","integer",NULL,NULL,"YES"
"tb_historico_jogos","num14","integer",NULL,NULL,"YES"
"tb_historico_jogos","num15","integer",NULL,NULL,"YES"
"tb_historico_jogos","id_loterias","integer",NULL,"1","NO"
"tb_historico_jogos","num_concurso","integer",NULL,NULL,"YES"
"tb_jogos_gerados","id_gerados","integer",NULL,"nextval('tb_jogos_gerados_id_seq'::regclass)","NO"
"tb_jogos_gerados","dt_inclusao","timestamp with time zone",NULL,"now()","NO"
"tb_jogos_gerados","dt_aposta","date",NULL,NULL,"YES"
"tb_jogos_gerados","num_concurso","integer",NULL,NULL,"YES"
"tb_jogos_gerados","num1","integer",NULL,NULL,"YES"
"tb_jogos_gerados","num2","integer",NULL,NULL,"YES"
"tb_jogos_gerados","num3","integer",NULL,NULL,"YES"
"tb_jogos_gerados","num4","integer",NULL,NULL,"YES"
"tb_jogos_gerados","num5","integer",NULL,NULL,"YES"
"tb_jogos_gerados","num6","integer",NULL,NULL,"YES"
"tb_jogos_gerados","num7","integer",NULL,NULL,"YES"
"tb_jogos_gerados","num8","integer",NULL,NULL,"YES"
"tb_jogos_gerados","num9","integer",NULL,NULL,"YES"
"tb_jogos_gerados","num10","integer",NULL,NULL,"YES"
"tb_jogos_gerados","num11","integer",NULL,NULL,"YES"
"tb_jogos_gerados","num12","integer",NULL,NULL,"YES"
"tb_jogos_gerados","num13","integer",NULL,NULL,"YES"
"tb_jogos_gerados","num14","integer",NULL,NULL,"YES"
"tb_jogos_gerados","num15","integer",NULL,NULL,"YES"
"tb_jogos_gerados","tot_acertos","integer",NULL,NULL,"YES"
"tb_jogos_gerados","id_loterias","integer",NULL,"1","NO"
"tb_jogos_gerados","dt_concurso","date",NULL,NULL,"YES"
"tb_jogos_gerados","numero_jogo","integer",NULL,NULL,"YES"
"tb_jogos_gerados","numeros","text",NULL,NULL,"YES"
"tb_jogos_gerados","num16","integer",NULL,NULL,"YES"
"tb_jogos_gerados","num17","integer",NULL,NULL,"YES"
"tb_jogos_gerados","num18","integer",NULL,NULL,"YES"
"tb_jogos_gerados","num19","integer",NULL,NULL,"YES"
"tb_jogos_gerados","num20","integer",NULL,NULL,"YES"
"tb_loterias","id_loterias","integer",NULL,"nextval('tb_loterias_id_loterias_seq'::regclass)","NO"
"tb_loterias","des_nome","character varying",40,NULL,"YES"
"tb_loterias","des_contexto","character varying",1000,NULL,"YES"
"tb_loterias","qt_numeros","integer",NULL,NULL,"YES"
"tb_loterias","dt_inclusao","date",NULL,NULL,"YES"
"tb_loterias","seg","boolean",NULL,NULL,"YES"
"tb_loterias","ter","boolean",NULL,NULL,"YES"
"tb_loterias","qua","boolean",NULL,NULL,"YES"
"tb_loterias","qui","boolean",NULL,NULL,"YES"
"tb_loterias","sex","boolean",NULL,NULL,"YES"
"tb_loterias","sab","boolean",NULL,NULL,"YES"
"tb_loterias","dom","boolean",NULL,NULL,"YES"
"tb_loterias","horario_sorteio","time without time zone",NULL,NULL,"YES"
"tb_loterias_preco","id_loterias","integer",NULL,NULL,"NO"
"tb_loterias_preco","id_loterias_preco","integer",NULL,"nextval('tb_loterias_preco_id_loterias_preco_seq'::regclass)","NO"
"tb_loterias_preco","qt_numeros_jogados","integer",NULL,NULL,"YES"
"tb_loterias_preco","vlr_aposta","numeric",NULL,NULL,"YES"
"tb_loterias_probabilidade","id_loterias","integer",NULL,NULL,"NO"
"tb_loterias_probabilidade","id_loterias_preco","integer",NULL,NULL,"NO"
"tb_loterias_probabilidade","id_loterias_probabilidade","integer",NULL,"nextval('tb_loterias_probabilidade_id_loterias_probabilidade_seq'::regclass)","NO"
"tb_loterias_probabilidade","qt_numeros_acertos","integer",NULL,NULL,"YES"
"tb_loterias_probabilidade","qt_numeros_jogados","integer",NULL,NULL,"YES"
"tb_loterias_probabilidade","qt_probabilidade","integer",NULL,NULL,"YES"
"tb_loterias_probabilidade","vlr_fator_premiacao","numeric",NULL,NULL,"YES"
"tb_lotofacil_resultados","id","integer",NULL,"nextval('tb_lotofacil_resultados_id_seq'::regclass)","NO"
"tb_lotofacil_resultados","numero_concurso","integer",NULL,NULL,"NO"
"tb_lotofacil_resultados","data_concurso","date",NULL,NULL,"NO"
"tb_lotofacil_resultados","data_proximo_concurso","date",NULL,NULL,"YES"
"tb_lotofacil_resultados","acumulado","boolean",NULL,NULL,"YES"
"tb_lotofacil_resultados","dezenas_sorteadas_ordem_sorteio","ARRAY",NULL,NULL,"YES"
"tb_lotofacil_resultados","lista_dezenas","ARRAY",NULL,NULL,"YES"
"tb_lotofacil_resultados","exibir_detalhamento_por_cidade","boolean",NULL,NULL,"YES"
"tb_lotofacil_resultados","indicador_concurso_especial","integer",NULL,NULL,"YES"
"tb_lotofacil_resultados","lista_municipio_uf_ganhadores","jsonb",NULL,NULL,"YES"
"tb_lotofacil_resultados","lista_rateio_premio","jsonb",NULL,NULL,"YES"
"tb_lotofacil_resultados","local_sorteio","character varying",255,NULL,"YES"
"tb_lotofacil_resultados","nome_municipio_uf_sorteio","character varying",255,NULL,"YES"
"tb_lotofacil_resultados","nome_time_coracao_mes_sorte","character varying",255,NULL,"YES"
"tb_lotofacil_resultados","numero_concurso_anterior","integer",NULL,NULL,"YES"
"tb_lotofacil_resultados","numero_concurso_final_0_5","integer",NULL,NULL,"YES"
"tb_lotofacil_resultados","numero_concurso_proximo","integer",NULL,NULL,"YES"
"tb_lotofacil_resultados","numero_jogo","integer",NULL,NULL,"YES"
"tb_lotofacil_resultados","observacao","text",NULL,NULL,"YES"
"tb_lotofacil_resultados","tipo_jogo","character varying",50,NULL,"YES"
"tb_lotofacil_resultados","tipo_publicacao","integer",NULL,NULL,"YES"
"tb_lotofacil_resultados","ultimo_concurso","boolean",NULL,NULL,"YES"
"tb_lotofacil_resultados","valor_arrecadado","numeric",NULL,NULL,"YES"
"tb_lotofacil_resultados","valor_acumulado_concurso_0_5","numeric",NULL,NULL,"YES"
"tb_lotofacil_resultados","valor_acumulado_concurso_especial","numeric",NULL,NULL,"YES"
"tb_lotofacil_resultados","valor_acumulado_proximo_concurso","numeric",NULL,NULL,"YES"
"tb_lotofacil_resultados","valor_estimado_proximo_concurso","numeric",NULL,NULL,"YES"
"tb_lotofacil_resultados","valor_saldo_reserva_garantidora","numeric",NULL,NULL,"YES"
"tb_lotofacil_resultados","valor_total_premio_faixa_um","numeric",NULL,NULL,"YES"
"tb_lotofacil_resultados","created_at","timestamp without time zone",NULL,"CURRENT_TIMESTAMP","YES"
"tb_metricas_jogos","id_metrica","integer",NULL,"nextval('tb_metricas_jogos_id_metrica_seq'::regclass)","NO"
"tb_metricas_jogos","id_loterias","integer",NULL,NULL,"YES"
"tb_metricas_jogos","id_gerados","integer",NULL,NULL,"YES"
"tb_metricas_jogos","score_paridade","numeric",NULL,NULL,"YES"
"tb_metricas_jogos","score_distribuicao","numeric",NULL,NULL,"YES"
"tb_metricas_jogos","score_historico","numeric",NULL,NULL,"YES"
"tb_metricas_jogos","score_final","numeric",NULL,NULL,"YES"
"tb_metricas_jogos","dt_avaliacao","timestamp without time zone",NULL,NULL,"YES"
"tb_metricas_qualidade","id_metrica","integer",NULL,"nextval('tb_metricas_qualidade_id_metrica_seq'::regclass)","NO"
"tb_metricas_qualidade","id_loterias","integer",NULL,NULL,"NO"
"tb_metricas_qualidade","tipo_metrica","character varying",50,NULL,"NO"
"tb_metricas_qualidade","valor","double precision",NULL,NULL,"NO"
"tb_metricas_qualidade","dt_calculo","timestamp without time zone",NULL,"CURRENT_TIMESTAMP","NO"
"tb_padroes_frequentes","id_padrao","integer",NULL,"nextval('tb_padroes_frequentes_id_padrao_seq'::regclass)","NO"
"tb_padroes_frequentes","id_loterias","integer",NULL,NULL,"YES"
"tb_padroes_frequentes","tipo_padrao","character varying",50,NULL,"YES"
"tb_padroes_frequentes","padrao","text",NULL,NULL,"YES"
"tb_padroes_frequentes","frequencia","integer",NULL,NULL,"YES"
"tb_padroes_frequentes","probabilidade","numeric",NULL,NULL,"YES"
"tb_padroes_frequentes","ultima_ocorrencia","timestamp without time zone",NULL,NULL,"YES"
"tb_padroes_identificados","id_padrao","integer",NULL,"nextval('tb_padroes_identificados_id_padrao_seq'::regclass)","NO"
"tb_padroes_identificados","id_loterias","integer",NULL,NULL,"NO"
"tb_padroes_identificados","nome_padrao","character varying",50,NULL,"NO"
"tb_padroes_identificados","valor","double precision",NULL,NULL,"NO"
"tb_padroes_identificados","dt_identificacao","timestamp without time zone",NULL,"CURRENT_TIMESTAMP","NO"
"tb_pesos_numeros","id_peso","integer",NULL,"nextval('tb_pesos_numeros_id_peso_seq'::regclass)","NO"
"tb_pesos_numeros","id_loterias","integer",NULL,NULL,"NO"
"tb_pesos_numeros","num_analisado","integer",NULL,NULL,"NO"
"tb_pesos_numeros","peso","double precision",NULL,NULL,"NO"
"tb_pesos_numeros","dt_calculo","timestamp without time zone",NULL,"CURRENT_TIMESTAMP","NO"
